"use client";
/**
 * Termini di Servizio, bilingue (it/en) in base alla lingua scelta nell'app.
 */
import Link from "next/link";
import { useI18n } from "@/lib/i18n";

const UPDATED_IT = "18 luglio 2026";
const UPDATED_EN = "July 18, 2026";
const CONTACT = "umasterinfo@gmail.com";

export function TermsContent() {
  const { lang } = useI18n();
  const en = lang === "en";
  const mail = (
    <a className="text-brand-600 hover:underline" href={`mailto:${CONTACT}`}>
      {CONTACT}
    </a>
  );

  return (
    <div className="mx-auto max-w-3xl px-6 py-12 text-gray-800 dark:text-gray-200">
      <Link href="/" className="text-sm text-brand-600 hover:underline">
        {en ? "← Back to uSocial" : "← Torna a uSocial"}
      </Link>

      <h1 className="mt-4 text-3xl font-bold">{en ? "Terms of Service" : "Termini di Servizio"}</h1>
      <p className="mt-1 text-sm text-gray-500">
        {en ? `Last updated: ${UPDATED_EN}` : `Ultimo aggiornamento: ${UPDATED_IT}`}
      </p>

      <div className="mt-8 space-y-6 leading-relaxed">
        {en ? (
          <>
            <section>
              <h2 className="text-xl font-semibold">1. Acceptance of terms</h2>
              <p>
                By using uSocial you accept these Terms of Service. If you do not accept them, do not
                use the service. uSocial is a self-hosted tool for creating, scheduling and publishing
                content to social networks.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">2. Description of the service</h2>
              <p>
                uSocial lets you draft posts, attach images and videos, schedule their publication and
                send them to the social accounts you connect (Facebook, Instagram, LinkedIn, YouTube,
                TikTok) through their official APIs. It also offers text suggestions generated by
                artificial intelligence.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">3. Account and security</h2>
              <p>
                You are responsible for keeping your credentials confidential and for all activity
                carried out through your account. You must provide accurate information when
                registering and keep your password secure.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">4. Connecting social accounts</h2>
              <p>
                When you connect a social account, you authorize uSocial to publish content on your
                behalf via the OAuth tokens issued by the platform. You can revoke this authorization
                at any time, either from uSocial or from the social platform&apos;s settings. You must
                comply with the terms and policies of the platforms you use.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">5. Content and your responsibilities</h2>
              <p>
                You are solely responsible for the content you create and publish through uSocial. You
                agree not to publish unlawful content, content that infringes third-party rights
                (including copyright), defamatory or misleading content, or content that violates the
                rules of the destination social platforms. uSocial is merely a publishing tool and does
                not control or endorse user content.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">6. Acceptable use</h2>
              <p>
                You agree not to use uSocial to send spam, abusive automated content or activity that
                violates applicable laws or the terms of the connected platforms. Misuse may compromise
                your social accounts.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">7. Third-party services</h2>
              <p>
                uSocial integrates with third-party services (the social network APIs and the AI
                provider). Use of those services is subject to their respective terms. We are not
                responsible for changes, malfunctions or interruptions of these external services.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">8. Disclaimer of warranties</h2>
              <p>
                uSocial is provided &quot;as is&quot;, without warranties of any kind. We do not
                guarantee that the service will always be available, error-free, or that scheduled
                publications will always succeed (e.g. due to social API limits or changes).
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">9. Limitation of liability</h2>
              <p>
                To the extent permitted by law, the operator of uSocial is not liable for direct or
                indirect damages arising from the use of, or inability to use, the service, including
                data loss or failure to publish content.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">10. Changes and termination</h2>
              <p>
                We may modify or discontinue the service and update these terms at any time. Changes
                will be posted on this page with the new update date. Continued use of the service
                constitutes acceptance of the updated terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">11. Contact</h2>
              <p>For questions about these Terms write to {mail}.</p>
            </section>
          </>
        ) : (
          <>
            <section>
              <h2 className="text-xl font-semibold">1. Accettazione dei termini</h2>
              <p>
                Utilizzando uSocial accetti i presenti Termini di Servizio. Se non li accetti, non
                utilizzare il servizio. uSocial è uno strumento self-hosted per creare, programmare e
                pubblicare contenuti sui social network.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">2. Descrizione del servizio</h2>
              <p>
                uSocial ti consente di redigere post, allegare immagini e video, programmarne la
                pubblicazione e inviarli agli account social che colleghi (Facebook, Instagram,
                LinkedIn, YouTube, TikTok) tramite le loro API ufficiali. Offre inoltre suggerimenti di
                testo generati tramite intelligenza artificiale.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">3. Account e sicurezza</h2>
              <p>
                Sei responsabile della riservatezza delle tue credenziali e di tutte le attività svolte
                tramite il tuo account. Devi fornire informazioni corrette in fase di registrazione e
                mantenere sicura la tua password.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">4. Collegamento agli account social</h2>
              <p>
                Quando colleghi un account social, autorizzi uSocial a pubblicare contenuti per tuo
                conto tramite i token OAuth rilasciati dalla piattaforma. Puoi revocare questa
                autorizzazione in qualsiasi momento, sia da uSocial sia dalle impostazioni della
                piattaforma social. Sei tenuto a rispettare i termini e le policy delle piattaforme che
                utilizzi.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">5. Contenuti e tue responsabilità</h2>
              <p>
                Sei l&apos;unico responsabile dei contenuti che crei e pubblichi tramite uSocial. Ti
                impegni a non pubblicare contenuti illeciti, che violino diritti di terzi (incluso il
                copyright), diffamatori, ingannevoli o che violino le regole delle piattaforme social di
                destinazione. uSocial è un semplice strumento di pubblicazione e non controlla né approva
                i contenuti degli utenti.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">6. Uso accettabile</h2>
              <p>
                Ti impegni a non usare uSocial per inviare spam, contenuti automatizzati abusivi o
                attività che violino le leggi applicabili o i termini delle piattaforme collegate. Un uso
                improprio può compromettere i tuoi account social.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">7. Servizi di terze parti</h2>
              <p>
                uSocial si integra con servizi di terze parti (le API dei social network e il provider di
                AI). L&apos;uso di tali servizi è soggetto ai rispettivi termini. Non siamo responsabili
                di modifiche, malfunzionamenti o interruzioni di questi servizi esterni.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">8. Esclusione di garanzie</h2>
              <p>
                uSocial è fornito &quot;così com&apos;è&quot;, senza garanzie di alcun tipo. Non
                garantiamo che il servizio sia sempre disponibile, privo di errori o che le pubblicazioni
                programmate vadano sempre a buon fine (ad es. per limiti o cambiamenti delle API dei
                social).
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">9. Limitazione di responsabilità</h2>
              <p>
                Nei limiti consentiti dalla legge, il titolare di uSocial non è responsabile per danni
                diretti o indiretti derivanti dall&apos;uso o dall&apos;impossibilità di usare il
                servizio, inclusa la perdita di dati o la mancata pubblicazione di contenuti.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">10. Modifiche e cessazione</h2>
              <p>
                Possiamo modificare o interrompere il servizio e aggiornare questi termini in qualsiasi
                momento. Le modifiche saranno pubblicate su questa pagina con la nuova data di
                aggiornamento. L&apos;uso continuato del servizio comporta l&apos;accettazione dei termini
                aggiornati.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold">11. Contatti</h2>
              <p>Per domande su questi Termini scrivi a {mail}.</p>
            </section>
          </>
        )}
      </div>

      <p className="mt-10 text-sm text-gray-500">
        {en ? "See also our " : "Vedi anche la nostra "}
        <Link href="/privacy" className="text-brand-600 hover:underline">
          Privacy Policy
        </Link>
        .
      </p>
    </div>
  );
}
